#!/usr/bin/python

import commands
import log
import ToolError
from Error import *

import utils

import pprint
from xml.etree.ElementTree import parse

class CppCheckXMLParser(object):
    def __init__(self, xml_file):
        self.xml_file = xml_file
        self.errors = {}

    def parse(self):
        """ parse the xml file. A sample xml result generated by cppcheck:

        <?xml version="1.0" encoding="UTF-8"?>
        <results>
        Checking CPrograms/test.c...
        <error file="test.c" line="5" id="unusedAllocatedMemory"
                severity="style" msg="..."/>
        <error file=".." line="6" id=".." severity="error"
                msg="Memory leak: f"/>
        </results>

        """

        tree = parse(self.xml_file)
        j = 0

        for e in tree.findall("error"):
            f = e.attrib["file"]
            l = e.attrib["line"]
            i = e.attrib["id"]
            s = e.attrib["severity"]
            m = e.attrib["msg"]

            self.errors[j]              = {}
            self.errors[j]["file"]      = f
            self.errors[j]["line"]      = l
            self.errors[j]["id"]        = i
            self.errors[j]["severity"]  = s
            self.errors[j]["msg"]       = m

            j += 1


        return self.errors

class CppCheck(object):

    CPPCHECK_PATH = None
    CPPCHECK_NAME = "cppcheck"

    def __init__(self, file_name):
        """ initialization
        """
        self.file_name = file_name      # source file to analyse
        self.errors    = []

        if not self.CPPCHECK_PATH:
            self.__cpp_check_path__()
        pass

    def __cpp_check_path__(self):
        """ find cppcheck path
        """
        p = utils.get_installed_path(self.CPPCHECK_NAME)
        if p:
            self.CPPCHECK_PATH = p
        else:
            log.log(3, CPPCHECK_NAME + " is not installed.")

    def is_installed(self):
        """ check if cppcheck tool is installed
        """
        r = self.__cpp_check_path__()
        if r == 0:
            return 0
        return 1

    def run_cpp_check(self, args):
        """ run cppcheck
        """
        # for now let's assume --enable=style argument, we might decide to
        # change it latter on
        default_args = " --enable=style "
        return utils.run_log_command(self.CPPCHECK_PATH + default_args + args)

    def add_error(self, error):
        """
        """
        self.errors.append(error)

    def analyse(self):
        """ analyse source code using cppcheck
        """
        xml = "/tmp/output.xml"
        args = " --xml " + self.file_name + " 2> " + xml

        log.log(3, "analysing cpp code using cppcheck")
        r, o = self.run_cpp_check(args)
        log.log(3, o)

        x       = CppCheckXMLParser(xml)
        errors  = x.parse()
        for en in errors:
            f = errors[en]["file"]
            l = errors[en]["line"]
            c = 0                   # cppcheck does not report column number
            te = errors[en]["msg"]
            id = errors[en]["id"]

            e = ToolError.cppcheck_error(id, l, c, f, te)   # get error object

            self.add_error(e)

        for e in self.errors:
            print e

        # pprint.pprint(errors)
